spring:
   profiles:
     active: prod
   datasource:
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@localhost:1521:orcl
     username: system
     password: Congriguang5918
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
  ##关闭缓存，及时刷新
   thymeleaf:
      cache: true
   #热部署生效
   devtools:
     restart:
       enabled: true
       additiaonal-paths: src/main/java
   #设置重新目录

   freemarker:
      template-loader-path: src/main/resources/templates
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attributes: request
      suffix: .ftl


